// <auto-generated />
using System;
using InvestimentosPessoais.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestimentosPessoais.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("InvestimentosPessoais.Domain.Entities.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestmentType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MaturityDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentType")
                        .HasDatabaseName("IX_Investments_Type");

                    b.ToTable("Investments", (string)null);

                    b.HasDiscriminator<string>("InvestmentType").HasValue("Investment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InvestimentosPessoais.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvestmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Shares")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentId");

                    b.HasIndex("PurchaseDate");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("InvestimentosPessoais.Domain.Entities.FixedIncome", b =>
                {
                    b.HasBaseType("InvestimentosPessoais.Domain.Entities.Investment");

                    b.Property<decimal>("ContractedRate")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("Indexer")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IndexerPercentage")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("FixedIncome");
                });

            modelBuilder.Entity("InvestimentosPessoais.Domain.Entities.VariableIncome", b =>
                {
                    b.HasBaseType("InvestimentosPessoais.Domain.Entities.Investment");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("DividendsReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("IX_VariableIncome_Ticker");

                    b.HasDiscriminator().HasValue("VariableIncome");
                });

            modelBuilder.Entity("InvestimentosPessoais.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("InvestimentosPessoais.Domain.Entities.Investment", "Investment")
                        .WithMany("Transactions")
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investment");
                });

            modelBuilder.Entity("InvestimentosPessoais.Domain.Entities.Investment", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
